### PR TITLE
add left right dividing passthrough

### PR DESCRIPTION
**Pull request by aginika**
Advise from @garaemon

BE CAREFUL THIS WILL CHANGE THE PASSTHROUGH LAUNCH

- divinding to two file.

left_right_dividing

### CODE REVIEW

**Comment by aginika** [comment]
new_passthrough

**Comment by aginika** [comment]
DON'T MERGE THIS UNTIL MOVEMENT BECOME PARALLEL

**Comment by aginika** [comment]
@wkentaro I renamed the filename to attention_divide.launch

**Comment by wkentaro** [comment]
I see.

**Comment by aginika** [comment]
Finally, jsk-ros-pkg/jsk_pcl_ros#891 fix the bug of attention clipper, so we can remove the passthrough filter. Therefore passthrough part and multiplay part in the above diagram has been removed.
It becomes a little bit lighter

**Comment by k-okada** [comment]
i have released both jsk_recognition and jsk_visualization and that would
be available from shadow-fixed very soon, so non pcl developer need to use
source code, use deb packages.

--
◉ Kei Okada

**Pull request merged**
