### PR TITLE
Add test code for object matching & result of sift test

### PR DESCRIPTION
**Pull request by wkentaro**
* 判別精度確認用の画像を追加
* 物体判別serverでのテストコード追加
* SIFTによる物体判別のテスト結果追加

### CODE REVIEW

**Comment by wkentaro** [comment]
issue: #155

**Comment by wkentaro** [comment]
次にやること
* テスト画像の追加
* Color Histogramでのテスト結果の追加

**Comment by wkentaro** [comment]
```
Matching for all objects with camera image

Usage
-----

    $ roslaunch jsk_2014_picking_challenge test_object_matching.launch \
        sift:=true
    or
    $ rolaunch jsk_2014_picking_challenge test_object_matching.launch \
        color_histogram:=true

```

**Comment by wkentaro** [comment]
マージお願いします。

**Comment by jiangjun0105** [comment]
If I want to run this test, do I just need run these two commands mentioned above? I mean the two ``roslaunch``.
But why there are so many ``process has died``?  it just looks like the figure below.

Do I need to run other programs, e.g. opening the camera, to provide some date to this testing program?
PS. the second `roslaunch` doesn't have `s`.

**Comment by wkentaro** [comment]
Because you have not run `catkin_make` or `catkin build`.
This process error is because of 
`ImportError: cannot import name StringEmpty`
and `StringEmpty` is comes from `StringEmpty.srv`

**Comment by jiangjun0105** [comment]
Thank you!
I ran `catkin build`, but failed.
Do you know how to solve this?
grasp_fail
Thank you for your help!

**Comment by wkentaro** [comment]
I dont use ohara-ros-pkg-private, so I dont know.

2015年3月25日水曜日、Jiang Jun<notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>>さんは書きました:

> Thank you!
> I ran catkin build, but failed.
> Do you know how to solve this?
> [image: grasp_fail]
> <https://cloud.githubusercontent.com/assets/8521008/6819752/aa84e492-d309-11e4-8e62-57996e145f23.png>
> Thank you for your help!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/pull/172#issuecomment-85891220>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by jiangjun0105** [comment]
So this error has nothing to do with your testing?
But I tried to run the commands again, getting the same error `roslaunch jsk_2014_picking_challenge test_sift_matching.launch knn_threshold:=0.8`
When the terminal only shows that "grasp" failed, does it means other packages were all compiled successfully?

**Comment by jiangjun0105** [comment]
I ran it in a new terminal, and it seems different.
Although it failed again, the error became `ImportError: No module named posedetection_msgs.msg
`
Is `posedetection_msgs.msg` made by you?

**Comment by wkentaro** [comment]
It is in jsk_common, I added posedetection_msgs to package.xml as depending
package.
https://github.com/start-jsk/2014-semi/pull/179
So please wait for it being merged.

On Wed, Mar 25, 2015 at 5:22 PM, Jiang Jun <notifications@github.com> wrote:

> I ran it in a new terminal, and it seems different.
> Although it failed again, the error became ImportError: No module named
> posedetection_msgs.msg
>
> Is posedetection_msgs.msg made by you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/pull/172#issuecomment-85914869>.
>



-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by k-okada** [comment]
please try
apt-get install ros-{hydro.indigo}-posedetection-msgs


--
◉ Kei Okada

**Comment by wkentaro** [comment]
__ANOTHER WAY TO RESOLVE__
It already have been merged, so I think you can run `rosdep install ...` to resolve the dependency.

**Comment by YuOhara** [comment]
> I dont use ohara-ros-pkg-private, so I dont know.

@jiangjun0105  
You can delete it or move it out of catkin_ws.
I think that codes were for tutorial(maybe I installed in your pc) and not needed.(And the codes in that pkg were almost moved into  or https://github.com/jsk-ros-pkg/jsk_recognition https://github.com/jsk-ros-pkg/jsk_demos

**Pull request merged**
