### PR TITLE
Add script to visualize sift keypoints

### PR DESCRIPTION
**Pull request by wkentaro**
You can visualize sift keypoints using scripts/visualize_sift.py.
This script is for **test** and **debug**.
Usage
-----
```sh
$ roslauch jsk_2014_picking_challenge visualize_sift.launch test:=true
$ rosservice call /image_publish_server `rospack find jsk_2014_picking_challenge`/data/paste.png
$ rosrun image_view image_view image:=/visualize_sift/output
```

### CODE REVIEW

**Comment by wkentaro** [comment]
frame0000

**Comment by wkentaro** [comment]
please merge.

**Comment by k-okada** [comment]
I'm afraid we have very similar node at https://github.com/jsk-ros-pkg/jsk_common/blob/master/posedetection_msgs/src/feature0d_view.cpp

**Comment by wkentaro** [comment]
I didn't know, thanks.

**Pull request merged**
